### ISSUE TITLE
Illegal character found

### ISSUE THREAD

**Issue by lemonysoft** [OHDSI/MedlineXmlToDatabase#13]
Hello again. How can I fix this? Is it ignorable?

> Processing pubmed19n0960.xml.gz
Illegal character found in name 'mml:math' in element 'MedlineCitation_KeywordList_Keyword'. Skipping field.
Processing pubmed19n0961.xml.gz

**Comment by schuemie** [comment]
Yes, that is the fix telling you it is doing its work.

**Comment by lemonsoftltd** [comment]
Thanks for the reply.
