### ISSUE TITLE
Document how many tables should be created

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/MedlineXmlToDatabase#4]
Would it be possible to mention briefly in readme, how many tables should have been created by the table creation step. (or even better, enumerating their names (if it is not too many to document)

Processing one XML file, I only see 2 tables. (seems too few)
![image](https://user-images.githubusercontent.com/7526119/30385066-feee1116-9873-11e7-8d5b-dbe91c86b4ac.png)

**Comment by vojtechhuser** [comment]
It seems to ignore many fields
![image](https://user-images.githubusercontent.com/7526119/30385091-1199c22e-9874-11e7-8170-7bf4799ae827.png)

**Comment by schuemie** [comment]
Hi @vojtechhuser ,

The number of tables depends on the structure of the XML files, which tends to change every so slightly every year. For 2017 I count 33 tables.

It seems like the analysis step didn't process all XML files, and therefore did not encounter all possible data elements. Can you confirm it processed all files? (currently there are 1,290 XML files for 2017)
