### ISSUE TITLE
where is cited pmids?

### ISSUE THREAD

**Issue by lemonsoftltd** [OHDSI/MedlineXmlToDatabase#8]
Hi,
I have downloaded .tar.gz files and converted all by **MedlineXMLToDatabase** tool. But I can't find PMIDs in commentscorrectslist table although they exist in original XML files.

Do you know where I can find them in which table? 
Thanks.

**Comment by schuemie** [comment]
I have 152,671,021 records in the table `medcit_commentscorrectionslist_commentscorrections`. Are there specific PMIDs you were expecting to see there that are missing?

**Comment by lemonsoftltd** [comment]
No. medcit_commentscorrectionslist_commentscorrections table has these fields: order, note, pmid, pmid_version, refsource and reftype. But cited reference PMIDs column is missing in the table. However original XML file has it as shown in following example.


```
<PubmedArticle>
    <MedlineCitation Status="MEDLINE" Owner="NLM">
        <PMID Version="1">23423664</PMID>
.
.
<CommentsCorrectionsList>
            <CommentsCorrections RefType="Cites">
                <RefSource>J Pers Assess. 1985 Feb;49(1):71-5</RefSource>
                <PMID Version="1">16367493</PMID>
            </CommentsCorrections>
            <CommentsCorrections RefType="Cites">
                <RefSource>J Pain Symptom Manage. 2008 Feb;35(2):203-13</RefSource>
                <PMID Version="1">18158230</PMID>
            </CommentsCorrections>
```

**Comment by schuemie** [comment]
Ach crivens! The PMID field in that table gets overwritten with the PMID corresponding to the parent citation.

The code is easily fixed: I am now [simply renaming such fields to 'Other_PMID"](4a47464056ca60ffc02c018512cc380ef563846b). However, it will require both the analysis and parsing to be completely redone.

**Comment by lemonsoftltd** [comment]
Are you goint to publish a new release?

**Comment by schuemie** [comment]
Yep, [here's the new release](https://github.com/OHDSI/MedlineXmlToDatabase/releases/tag/v0.3.4).

**Comment by lemonsoftltd** [comment]
Thanks a lot, really appreciated.
